<?php

use CRM_Geocoder_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Geocoders',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Geocoders',
        'label' => E::ts('Geocoders'),
        'form_values' => NULL,
        'mapping_id' => NULL,
        'search_custom_id' => NULL,
        'api_entity' => 'Geocoder',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'name',
            'title',
            'class',
            'is_active',
            'weight',
            'api_key',
            'url',
            'required_fields',
            'retained_response_fields',
            'datafill_response_fields',
            'threshold_standdown',
            'threshold_last_hit',
            'valid_countries',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
        'expires_date' => NULL,
        'description' => NULL,
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Geocoders_SearchDisplay_Geocoders_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Geocoders_Table_1',
        'label' => E::ts('Geocoders Table 1'),
        'saved_search_id.name' => 'Geocoders',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [
            [
              'is_active',
              'DESC',
            ],
            [
              'weight',
              'ASC',
            ],
          ],
          'limit' => 50,
          'pager' => [
            'hide_single' => TRUE,
          ],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('Geocoder ID'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'name',
              'dataType' => 'String',
              'label' => E::ts('Name'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'title',
              'dataType' => 'String',
              'label' => E::ts('Title'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'class',
              'dataType' => 'String',
              'label' => E::ts('Class'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Enabled'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'weight',
              'dataType' => 'Integer',
              'label' => E::ts('Weight'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'api_key',
              'label' => E::ts('API Key'),
            ],
            [
              'type' => 'field',
              'key' => 'url',
              'dataType' => 'String',
              'label' => E::ts('Url'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'required_fields',
              'dataType' => 'String',
              'label' => E::ts('Required Fields'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'retained_response_fields',
              'dataType' => 'String',
              'label' => E::ts('Retained Response Fields'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'datafill_response_fields',
              'dataType' => 'String',
              'label' => E::ts('Datafill Response Fields'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'threshold_standdown',
              'dataType' => 'Integer',
              'label' => E::ts('Threshold Standdown'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'threshold_last_hit',
              'dataType' => 'Timestamp',
              'label' => E::ts('Threshold Last Hit'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'valid_countries',
              'dataType' => 'String',
              'label' => E::ts('Valid Countries'),
              'sortable' => TRUE,
            ],
          ],
          'actions' => FALSE,
          'classes' => [
            'table',
            'table-striped',
          ],
        ],
        'acl_bypass' => FALSE,
      ],
      'match' => [
        'name',
        'saved_search_id',
      ],
    ],
  ],
];
